name: "Setup and install"
description: "Common setup steps for Actions"

runs:
  using: composite
  steps:
    - name: Cache turbo build setup
      uses: actions/cache@v4
      with:
        path: .turbo
        key: ${{ runner.os }}-turbo-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-turbo-

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2

    - name: Setup Node.js for npm OIDC
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        registry-url: 'https://registry.npmjs.org'

    - name: Update npm for OIDC support
      shell: bash
      run: npm install -g npm@latest

    - name: Install dependencies
      shell: bash
      run: bun install
