name: "Update Monitoring Services"
description: "Create PostHog annotation for CLI release"

inputs:
  version:
    description: "Version number for the release"
    required: true

runs:
  using: composite
  steps:
    - name: Create PostHog release annotation
      shell: bash
      env:
        POSTHOG_PERSONAL_API_KEY: ${{ env.POSTHOG_PERSONAL_API_KEY }}
        NEXT_PUBLIC_POSTHOG_HOST: ${{ env.NEXT_PUBLIC_POSTHOG_HOST }}
      run: |
        curl -X POST https://${{ env.NEXT_PUBLIC_POSTHOG_HOST }}/api/projects/@current/annotations/ \
        -H "Authorization: Bearer ${{ env.POSTHOG_PERSONAL_API_KEY }}" \
        -H "Content-Type: application/json" \
        -d '{
          "content": "CLI v${{ inputs.version }} released",
          "scope": "project",
          "date_marker": "'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'"
        }'