[build]
entrypoints = ["./src/cli.tsx"]
outdir = "./bin"
# minify = true
sourcemap = true
target = "${BUN_BUILD_TARGET:-bun}"  # Default to 'bun' if BUN_BUILD_TARGET is not set
main-fields = ["bin", "module", "main"]
# bytecode = true

[env]
process.env.NEXT_PUBLIC_SUPABASE_URL = "${NEXT_PUBLIC_SUPABASE_URL}"
process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY = "${NEXT_PUBLIC_SUPABASE_ANON_KEY}"
process.env.NEXT_PUBLIC_POSTHOG_KEY = "${NEXT_PUBLIC_POSTHOG_KEY}"
process.env.NEXT_PUBLIC_POSTHOG_HOST = "${NEXT_PUBLIC_POSTHOG_HOST}"
process.env.NEXT_PUBLIC_APP_TYPE = "${NEXT_PUBLIC_APP_TYPE}"
process.env.NEXT_PUBLIC_APP_ENV = "${NEXT_PUBLIC_APP_ENV}"
process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY = "${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}"
process.env.NEXT_PUBLIC_API_URL = "${NEXT_PUBLIC_API_URL}"