apiVersion: v1
kind: ConfigMap
metadata:
  name: unhook-config
  namespace: unhook
data:
  # Application configuration
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  
  # Service ports
  WEB_PORT: "3000"
  ROUTER_PORT: "8080"
  
  # Redis configuration
  REDIS_HOST: "unhook-redis"
  REDIS_PORT: "6379"
  
  # PostgreSQL configuration
  POSTGRES_HOST: "unhook-postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "unhook"
  
  # Public URLs (update these based on your deployment)
  NEXT_PUBLIC_API_URL: "https://your-domain.com"
  NEXT_PUBLIC_CLERK_SIGN_IN_URL: "/sign-in"
  NEXT_PUBLIC_CLERK_SIGN_UP_URL: "/sign-up"
  NEXT_PUBLIC_POSTHOG_HOST: "https://app.posthog.com"