apiVersion: apps/v1
kind: Deployment
metadata:
  name: unhook-web
  namespace: unhook
spec:
  replicas: 2
  selector:
    matchLabels:
      app: unhook-web
  template:
    metadata:
      labels:
        app: unhook-web
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox:1.35
        command: ['sh', '-c', 'until nc -z unhook-postgres 5432; do echo waiting for postgres; sleep 2; done']
      containers:
      - name: web
        image: unhook/web:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: unhook-config
              key: NODE_ENV
        - name: PORT
          value: "3000"
        - name: POSTGRES_URL
          valueFrom:
            secretKeyRef:
              name: unhook-secrets
              key: POSTGRES_URL
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: unhook-secrets
              key: REDIS_URL
        - name: CLERK_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: unhook-secrets
              key: CLERK_SECRET_KEY
        - name: CLERK_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: unhook-secrets
              key: CLERK_WEBHOOK_SECRET
        - name: NEXTAUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: unhook-secrets
              key: NEXTAUTH_SECRET
        - name: WEBHOOK_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: unhook-secrets
              key: WEBHOOK_ENCRYPTION_KEY
        - name: POSTHOG_KEY
          valueFrom:
            secretKeyRef:
              name: unhook-secrets
              key: POSTHOG_KEY
        - name: NEXTAUTH_URL
          value: "https://your-domain.com"
        - name: WEBHOOK_BASE_URL
          value: "https://your-domain.com"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: unhook-web
  namespace: unhook
spec:
  selector:
    app: unhook-web
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP