name: CLI Release

on:
  workflow_run:
    workflows: ["CLI Build"]
    types:
      - completed
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: unhook-*
          path: apps/cli/bin
          run-id: ${{ github.event.workflow_run.id }}

      - uses: ./tooling/github/cli/release
        with:
          version: ${{ github.event.workflow_run.run_number }}