name: CLI Release

on:
  workflow_run:
    workflows: [CLI Build, Typecheck & Format, Changeset]
    types:
      - completed
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  POSTHOG_PERSONAL_API_KEY: ${{ secrets.POSTHOG_PERSONAL_API_KEY }}
  NEXT_PUBLIC_POSTHOG_HOST: ${{ secrets.NEXT_PUBLIC_POSTHOG_HOST }}

jobs:
  release:
    name: Release CLI
    # Only run if Changeset workflow succeeded and it was a version bump
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      contains(github.event.workflow_run.head_commit.message, 'chore: version packages')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Need full history for Changesets
          fetch-depth: 0

      - name: Setup Environment
        uses: ./tooling/github/setup

      - name: Get version from package.json
        id: version
        run: |
          VERSION=$(node -p "require('./apps/cli/package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: unhook-*
          path: dist
          run-id: ${{ github.event.workflow_run.id }}

      - name: Update Monitoring
        uses: ./tooling/github/cli/monitoring
        with:
          version: ${{ steps.version.outputs.version }}